### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by rickysou** [zekunyan/TTGEmojiRate#3]
hi, thanks for sharing this fantastic emoji rating. I used it , but i occurred a memory problem. when it load the view the memory would rush to 270M, and then it will crash on 1g ram device. how could i solve this problem, thanks?
### UPDATE

the memory problem is caused by loading a pdf file, not the TTEmojiRting. sorry for bothering and really thanks to zekunyan's patient answers

**Comment by zekunyan** [comment]
I will fix it ! Thank you !

**Comment by zekunyan** [comment]
@rickysou I have fixed the memory problem in the new version 0.1.6. You can try it :)

**Comment by rickysou** [comment]
great thanks for your work. i test it on iPhone memory cost 196m , it is good. but test on 1g ram device(ipod 5) still crash,,,you test on 1g device, it runs fine?

**Comment by zekunyan** [comment]
I created 100 EmojiRateView instances like this:

**Comment by zekunyan** [comment]
I have tested it by creating 100 EmojiRateView instances in TTGEmojiRate Demo like this:

```
for i in 0...100 {
    let tmp = EmojiRateView.init(frame: CGRectMake(20, (CGFloat)(i * 10), 200, 200))
    self.view.addSubview(tmp)
}
```

It only cost `7.1MB` memory on my iPhone 6.

So maybe it's some other reason that lead to your memory problem. :)

**Comment by rickysou** [comment]
wow, i will check that. if so, really sorry for troubling you

**Comment by zekunyan** [comment]
You are welcome. :)
